# Site settings
title: Mertcan Ekren
header-img: img/header-background.jpg
email: mertcanekren@gmail.com
description: "Web Developer"
baseurl: "/blog/"
url: "http://mertcanekren.com/"
twitter_username: mertcanekren
github_username:  mertcanekren
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
